replicaCount: 2
image:
  repository: cr.yandex/crp38qtcgb3m048rbf4u/guestbook # замени на свой registry
  tag: 8f1cf8bd391eda941e8d285a801cbee0f99f6c42
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  className: nginx
  host: guestbook.vika-cloud.ru
  tls:
    enabled: true
    issuer: letsencrypt-prod
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
postgresql:
  enabled: true
  auth:
    username: guestbook
    password: "" # заполняется в CI или через секрет
    database: guestbook
  primary:
    persistence:
      enabled: true
      size: 5Gi
monitoring:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
  dashboard:
    enabled: true
