replicaCount: 2
image:
  repository: ghcr.io/va-lekseeva/final-app
  tag: 2733b2a52842deb8e80675a7859ec99d3b23ad39
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: guestbook.vika-cloud.ru
  tls:
    enabled: true
    issuer: letsencrypt-prod
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
postgresql:
  image: postgres:16-alpine
  auth:
    username: guestbook
    password: guestbook
    database: guestbook
  primary:
    persistence:
      enabled: true
      size: 5Gi
monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s
  prometheusRule:
    enabled: true
  dashboard:
    enabled: true
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 70
podDisruptionBudget:
  enabled: false
  minAvailable: 1
backup:
  enabled: true
  schedule: "0 3 * * *"
